services:
  # PostgreSQL Service
  postgres_db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: '${DATABASE_USERNAME}:user'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}:password'
      POSTGRES_DB: '${DATABASE_NAME}:prod_db'
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # NestJS Application
  nest_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    restart: always
    ports:
      - '3001:3001' # Aplikasi akan berjalan di port 3000
    depends_on:
      - postgres_db
    volumes:
      - ./src:/app/src

volumes:
  postgres_data:
