name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.11.0'  # Ganti dengan versi Node.js yang Anda gunakan

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          export DOCKER_BUILDKIT=1
          docker build -t edysupardi18/product-api:latest .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push edysupardi18/product-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_PATH: ${{ secrets.VPS_PATH }}
        run: |
          # Membuat direktori .ssh jika belum ada
          mkdir -p ~/.ssh
          
          # Menambahkan kunci host VPS ke known_hosts
          ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts

          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          
          ssh -i private_key $VPS_USER@$VPS_HOST << EOF
            # Navigasi ke direktori proyek
            cd $VPS_PATH

            # Tarik image terbaru
            docker pull edysupardi18/product-api:latest
            
            # Hentikan dan hapus container yang sedang berjalan
            docker-compose down
            
            # Jalankan docker-compose untuk memulai aplikasi
            docker-compose up -d
          EOF
