name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Ganti dengan nama branch yang Anda gunakan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.11.0'  # Ganti dengan versi Node.js yang Anda gunakan

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          scp -i private_key -r ./* $VPS_USER@$VPS_HOST:/path/to/your/project
          ssh -i private_key $VPS_USER@$VPS_HOST "cd /path/to/your/project && npm install && npm run build && pm2 restart your-app"
